name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Create results directory
      run: mkdir -p test_results

    - name: Run tests
      run: dotnet test --no-build --logger "trx;LogFileName=test_results.trx"

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate HTML report
      run: reportgenerator "-reports:TestResults/test_results.trx" "-targetdir:test_results_html"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test_results_html
